[french]
3a6ee618 = "Data science usage"
7f301bcd = "Will increase use in the future"
744be677 = "At which stage of the deal process"
08137f0d = "Main usage reason"
78cf2a96 = "Data sources"
263b6acc = "Technologies used"
58c1a686 = "Effect on investments"
286b67e7 = "How ?"
634bd84a = "Implementation time"
6dc00bfd = "Internal resistance"
"63097758" = "Finds business/tech profiles"
2b356f49 = "Can be contacted for an interview"

[english]
3a6ee618 = "Data science usage"
7f301bcd = "Will increase use in the future"
744be677 = "At which stage of the deal process"
08137f0d = "Main usage reason"
78cf2a96 = "Data sources"
263b6acc = "Technologies used"
58c1a686 = "Effect on investments"
286b67e7 = "How ?"
634bd84a = "Implementation time"
6dc00bfd = "Internal resistance"
"63097758" = "Finds business/tech profiles"
2b356f49 = "Can be contacted for an interview"
