[passwords]
# Follow the rule: username = "password"
username = "<password>"

[api]
default_scopes = ["<list of scopes to use on google api>"]
[api.service_account]
"private_key" = "<private key here>"
"type" = "service_account"
"project_id" = "<google api project id>"
"private_key_id" = "<private key id here>"
"client_email" = "<client email here>"
"client_id" = "<client id here>"
"auth_uri" = "<auth uri>"
"token_uri" = "<token uri>"
"auth_provider_x509_cert_url" = "<certificate provider here>"
"client_x509_cert_url" = "<google client url>"

[forms]
french_form_id = "<id of the gsheet form used for the french survey>"
english_form_id = "<id of the gsheet form used for the english survey>"

[sheets]
gsheet_tracking_id = "<id of the gsheet used to track survey answers>"
gsheet_refinitiv_id = "<id of the gsheet containing financial data>"
